In [37]:
import torch
import torch.nn as nn

# adapter_up = nn.Linear(8, 768, bias=False)
# nn.init.eye_(adapter_up.weight)

# inv = torch.linalg.svd(adapter_up.weight)

### Upsampling, W: m*n, m>n
### Condition: W has full column rank
W = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float32)
# W = torch.tensor([[1, 2], [2, 4], [3, 6]], dtype=torch.float32)
# x = torch.tensor([[1, 2], [4, 5]], dtype=torch.float32)
x = torch.tensor([[0.0002, 0], [0.0001, 2]], dtype=torch.float32)

### Downsampling, W: m*n, m<n
# W = torch.tensor([[1, 2, 3], [3, 4, 5]], dtype=torch.float32)
# # x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
# x = torch.tensor([[1, 0, 0], [0, 2, 3]], dtype=torch.float32)

y = torch.matmul(x, W.T)

U, S, Vh = torch.linalg.svd(W, full_matrices=False)

print(U.shape, S.shape, Vh.shape)

S_inv = torch.diag(1 / S)
# Pad the matrix to the desired size
# S_inv = torch.nn.functional.pad(S_inv, (0, U.size(-1) - S_inv.size(-1), 0, Vh.size(-1) - S_inv.size(-1)))
# print(S_inv.shape)

W_inv = Vh.T @ S_inv @ U.T
W_inv_T = U @ S_inv @ Vh

back_x = torch.matmul(y, W_inv_T)

print(x)
print(back_x)

print(W_inv.T)
print(W_inv_T)

torch.Size([3, 2]) torch.Size([2]) torch.Size([2, 2])
tensor([[2.0000e-04, 0.0000e+00],
        [1.0000e-04, 2.0000e+00]])
tensor([[2.0000e-04, 2.8320e-10],
        [9.9261e-05, 2.0000e+00]])
tensor([[-1.3333,  1.0833],
        [-0.3333,  0.3333],
        [ 0.6667, -0.4167]])
tensor([[-1.3333,  1.0833],
        [-0.3333,  0.3333],
        [ 0.6667, -0.4167]])


In [8]:
import torch

s = torch.tensor([1, 2, 3])
m = 5
# s.expand(m, -1)

torch.diag(s)

tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])